// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

const createChunk = `-- name: CreateChunk :one
INSERT INTO chunks (document_id, content, embedding)
VALUES ($1, $2, $3)
RETURNING id, document_id, content, embedding, created_at
`

type CreateChunkParams struct {
	DocumentID uuid.UUID       `json:"document_id"`
	Content    string          `json:"content"`
	Embedding  pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, createChunk, arg.DocumentID, arg.Content, arg.Embedding)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const searchSimilarChunks = `-- name: SearchSimilarChunks :many
SELECT
    id,
    document_id,
    content,
    created_at,
    (embedding <=> $1)::float8 AS distance
FROM chunks
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchSimilarChunksParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	Limit     int32           `json:"limit"`
}

type SearchSimilarChunksRow struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
	Distance   float64   `json:"distance"`
}

func (q *Queries) SearchSimilarChunks(ctx context.Context, arg SearchSimilarChunksParams) ([]SearchSimilarChunksRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarChunks, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSimilarChunksRow{}
	for rows.Next() {
		var i SearchSimilarChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Content,
			&i.CreatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
