// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (title)
VALUES ($1)
RETURNING id, title, created_at
`

func (q *Queries) CreateDocument(ctx context.Context, title string) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, title)
	var i Document
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, created_at FROM documents
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, title, created_at FROM documents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
