// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error)
	CreateDocument(ctx context.Context, title string) (Document, error)
	GetDocument(ctx context.Context, id uuid.UUID) (Document, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	SearchSimilarChunks(ctx context.Context, arg SearchSimilarChunksParams) ([]SearchSimilarChunksRow, error)
}

var _ Querier = (*Queries)(nil)
