// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/answers": {
            "post": {
                "description": "Asks Claude to score the answer and return structured feedback plus a follow-up question.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "interview"
                ],
                "summary": "Evaluate a candidate's answer",
                "parameters": [
                    {
                        "description": "Question and the candidate's answer",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interview.AnswerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_interview.Evaluation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/documents": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "List ingested documents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max documents to return (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of documents to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_document.Document"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Chunks the content, embeds each chunk locally via Ollama, and stores the vectors for retrieval.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Ingest a document",
                "parameters": [
                    {
                        "description": "Title and content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_document.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_document.Document"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/questions": {
            "post": {
                "description": "Embeds the topic, finds the most similar ingested chunks, and asks Claude for one question grounded in them.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "interview"
                ],
                "summary": "Generate an interview question (RAG)",
                "parameters": [
                    {
                        "description": "Topic and level",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interview.QuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_interview.Question"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_giovanysievert_ask-anything_internal_httputil.ErrorBody": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_giovanysievert_ask-anything_internal_httputil.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_giovanysievert_ask-anything_internal_httputil.ErrorBody"
                }
            }
        },
        "internal_document.CreateRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "minLength": 1,
                    "example": "FlatList renders large lists efficiently. Use getItemLayout, keyExtractor, windowSize..."
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "React Native FlatList"
                }
            }
        },
        "internal_document.Document": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_interview.AnswerRequest": {
            "type": "object",
            "required": [
                "answer",
                "question"
            ],
            "properties": {
                "answer": {
                    "type": "string",
                    "minLength": 1,
                    "example": "Use getItemLayout, memoize renderItem, switch to FlashList."
                },
                "question": {
                    "type": "string",
                    "minLength": 1,
                    "example": "How would you optimize a slow FlatList?"
                }
            }
        },
        "internal_interview.Evaluation": {
            "type": "object",
            "properties": {
                "feedback": {
                    "type": "string"
                },
                "missing_points": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "next_question": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "weak_topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_interview.Question": {
            "type": "object",
            "properties": {
                "question": {
                    "type": "string"
                }
            }
        },
        "internal_interview.QuestionRequest": {
            "type": "object",
            "required": [
                "level",
                "topic"
            ],
            "properties": {
                "level": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1,
                    "example": "senior"
                },
                "topic": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "react native flatlist"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ask-anything API",
	Description:      "AI-powered technical-interview API. Ingest documents, then generate RAG-grounded interview questions and evaluate candidate answers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
